### PR TITLE
BUG: AccountFlags.is_clawback_enabled is optional

### PR DESCRIPTION
**Pull request by MartinThoma**

### CODE REVIEW

**Comment by MartinThoma** [comment]
I just had the issue that parsing the response of a horizon node failed as `is_clawback_enabled` was not present in the account flags.

I'm not sure if this should count as `None` / `False` / `True`. I would prefer not to have `None`

**Comment by overcat** [comment]
Hello, the latest version of stellar-model corresponds to Horizon v2.5.2. In Horizon v2.5.2, auth_clawback_enabled absolutely exists. Therefore, users need to choose the corresponding stellar-model version according to the Horizon version they are using.

https://github.com/StellarCN/stellar-model/blob/main/CHANGELOG.rst#020b0-horizon-v252

**Comment by MartinThoma** [comment]
Ah, that makes sense. It would be good to have a table which clearly denotes the compatibility of stelar-model with the horizion version(s)

**Comment by MartinThoma** [comment]
Another option would be to keep the version of stellar-model with the horizon versions in sync. Hence stellar-model should be in version 2.6.1 now - maybe keep major and minor equal, but vary the patch number.

**Comment by overcat** [comment]
> Another option would be to keep the version of stellar-model with the horizon versions in sync. Hence stellar-model should be in version 2.6.1 now - maybe keep major and minor equal, but vary the patch number.

I love this idea, maybe we can use this format - `X.Y.Z.postN`.

**Comment by MartinThoma** [comment]
Is there a way to know from the outside which version a horizon node is using? Does the stellar-sdk have an option to query this information?

**Comment by MartinThoma** [comment]
I've just seen that you actually denoted the horizon version: https://github.com/StellarCN/stellar-model/blob/main/CHANGELOG.rst#020b0-horizon-v252 - I just didn't notice it before.

I'll close this PR as it's not improving the project.

**Comment by overcat** [comment]
> Is there a way to know from the outside which version a horizon node is using? Does the stellar-sdk have an option to query this information?

You can get the version information by visiting the root path of the horizon instance.

https://horizon.stellar.org/ 

"horizon_version": "2.6.1-71350e687eaf44ae5badfabb545b8e754529c2d3"

**Comment by MartinThoma** [comment]
It would be absolutely amazing if one could do this dynamically:

1. Fetch the current horizon version
2. Tell stellar-model which version one needs
3. Use the specific pydantic model versions throughout the code

In a project I'm currently working on the current behavior causes an issue. I want to use stellar-model in order to access attributes instead of dictionary keys and thus gain confidence that the code is correct / get better editor support.

I would like something like "I know the horizon server is version 1.2.3 or later". Attributes which are introduced in later versions should not cause an issue.

**Comment by overcat** [comment]
I like your suggestion, but this will result in an additional http request every time you access the data, because the SDK must access the root node to get the version number.

In addition, we assume that you are using a specific version of stellar-model, and horizon is upgraded to a new version at this time. At this time, you don't need to upgrade stellar-model, and you don't have to worry about data parsing failure. You only need to upgrade the stellar-model when you need to use the new fields added by the new version of horizon, or when the horizon contains breaking changes.

**Comment by overcat** [comment]
If you are building a larger Stellar-based project, I suggest you run a horizon instance yourself.

**Pull request closed without merging**
